
[[redirects]]
    from = "https://www.kattow.dev/*"
    to = "https://kattow.dev/*"
    status = 301

[[redirects]]
    from = "https://www.kattow.com/*"
    to = "https://kattow.dev/*"
    status = 301

[[redirects]]
    from = "https://kattow.com/*"
    to = "https://kattow.dev/*"
    status = 301

# Headers to return with requests for the specified paths
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
      public,
      max-age=0,
      must-revalidate'''

[[headers]]
    for = "/static/*"

  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''